# Generated by Django 3.2.13 on 2023-05-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='genres',
            field=models.CharField(default='Actions', max_length=255),
        ),
    ]
