# Generated by Django 3.2.13 on 2023-05-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='genres',
        ),
    ]
