# Generated by Django 3.2.12 on 2023-04-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movies',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
