# Generated by Django 3.2.18 on 2023-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_comment_star_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star_score',
            field=models.FloatField(null=True),
        ),
    ]
