# Generated by Django 3.2.18 on 2023-05-24 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_allmovie_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmovie',
            name='like_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
