# Generated by Django 3.2.18 on 2023-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_allmovie_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
