# Generated by Django 3.2.13 on 2023-05-24 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_moviedetail_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmovie',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allmovie',
            name='like_users',
            field=models.ManyToManyField(related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
