# Generated by Django 3.2.18 on 2023-05-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20230524_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allmovie',
            old_name='username',
            new_name='user',
        ),
    ]
