# Generated by Django 3.2.18 on 2023-05-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_allmovie_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmovie',
            name='user',
        ),
    ]
