# Generated by Django 3.2.13 on 2023-05-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_allmovie_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_profile_img',
        ),
        migrations.AlterField(
            model_name='allmovie',
            name='release_date',
            field=models.DateField(max_length=500),
        ),
    ]
